fix: Missing hovered color changes for CrystalColor family
linuxdeepin/dtkdeclarative pull request #111
Opened 2023-03-01 08:53 UTC by 18202781743

ColorSelector.hovered was disabled for all family.
  The code should be similar to the following：
```
  enableBackgroundHovered: D.ColorSelector.family ===
D.Palette.CommonColor ? false : undefined

  D.ColorSelector.hovered: control.enableBackgroundHovered
```
  But ColorSelector is attached property, and it's property is
built by dynamic metaobject, it causes that dynamic property can't fetch binding express unless static value.
 I don't have a best way to deal with the problem.

 TODO: Support binding express for ColorSelector set value.

2023-03-01 10:15 UTC, asterwyx commented on src/qml/BoxPanel.qml
> +    property bool enableBackgroundHovered: false
可以叫backgroundFollowsHovered.

2023-03-02 01:24 UTC, zccrs requested changes

2023-03-02 01:24 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +        if (_c == QMetaObject::ResetProperty && _id >= propertyOffset()) {
在什么情况下会出现ResetProperty操作时的id小于propertyOffset()?

2023-03-02 01:58 UTC, 18202781743 commented on src/private/dquickcontrolpalette.cpp
> +        if (_c == QMetaObject::ResetProperty && _id >= propertyOffset()) {
属性是自己声明的，而不是父类的时候就会小于，
ColorSelector.hovered: undefined，对hovered的reset时，hovered的id就小于propertyoffset

2023-03-02 02:44 UTC, zccrs requested changes

2023-03-02 02:44 UTC, zccrs commented on src/qml/BoxPanel.qml
> +    property bool enableBackgroundHovered: false
+1

2023-03-02 02:44 UTC, zccrs commented on src/qml/ButtonPanel.qml
> +    enableBackgroundHovered: D.ColorSelector.family !== D.Palette.CommonColor
可以加个注释说明family是CommonColor时为什么不需要background 的 hover效果

2023-03-02 07:39 UTC, zccrs requested changes

2023-03-02 07:39 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +        if (_c == QMetaObject::ResetProperty && _id >= propertyOffset()) {
这个改动单独一个commit, 不过PR可以跟这个复用一个。

2023-03-10 09:20 UTC, 18202781743 commented
在 https://github.com/linuxdeepin/dtkdeclarative/pull/115 提交里修复

2023-03-10 09:20 UTC, closed without merging