feat: Forward shaders in qt6
linuxdeepin/dtkdeclarative pull request #146
Opened 2023-06-20 01:53 UTC by 18202781743

Adapt to changes in QSGMaterialShader and add shaders_ng.

Issue: https://github.com/linuxdeepin/dtk/issues/87

2023-06-25 02:21 UTC, zccrs reviewed
这个提交要编译后测试运行效果，功能都正常才可以合入

2023-06-25 02:21 UTC, zccrs commented on src/CMakeLists.txt
> +if(EnableDtk6)
这里不应该是判断dtk6，应该判断 Qt6, 只不过是从 DTK6 开始才支持 Qt6，它们俩是这样的关系，但不能等价于DTK6就一定是Qt6。

2023-06-25 02:21 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +class OpaqueTextureMaterialShader : public QSGOpaqueTextureMaterialRhiShader
为什么不直接用 QSGMaterialShader 了

2023-06-25 02:21 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 64, &maskScale, 4);
这些数字分别是啥意义？

2023-06-25 02:21 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +    if (binding != 2)
2是指？

2023-06-25 02:21 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 76, &opacity, 4);
76是？

2023-06-25 02:21 UTC, zccrs commented on src/private/drectanglenode.cpp
> +#include <QtGui/private/qshader_p.h>
需要包到版本判断里吗

2023-06-25 02:37 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 64, &maskScale, 4);
例如 src/shaders_ng/quickitemviewport-opaque.frag
```
layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    vec2 maskScale;
    vec2 maskOffset;
    vec2 sourceScale;
} ubuf;
```
代表成员变量在这个结构体的偏移量，mat4是64个字节

2023-06-25 02:38 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +    if (binding != 2)
2指的是第二个uniform变量，
```
layout(binding = 2) uniform sampler2D mask;
```

2023-06-25 02:38 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 76, &opacity, 4);
同上，

2023-06-25 02:40 UTC, 18202781743 commented on src/private/drectanglenode.cpp
> +#include <QtGui/private/qshader_p.h>
应该需要，只测试了5.15和6.2的，它是5.14引入的，

2023-06-25 02:52 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +class OpaqueTextureMaterialShader : public QSGOpaqueTextureMaterialRhiShader
看我们OpaquetextureMaterialShader写的内容，跟QSGOpaqueTextureMaterialRhiShader功能差不多，应该可以直接继承QSGOpaqueTextureMaterialRhiShader，

2023-06-27 01:44 UTC, zccrs requested changes

2023-06-27 01:44 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 64, &maskScale, 4);
那定义一个宏，或者是 constexpr 的变量来使用，在它们的命名上体现含义。
另外，最后的这个4是不是应该用 sizeof(maskScale)?

2023-06-27 01:44 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 64, &maskScale, 4);
其它地方同理，不过我觉得这个是不是用 QDataStream 来做，省得自己计算每个变量相对于上个变量的偏移量，如果 QDataStream 不适用，也可以自己封装一个可变参数的模板函数来做。

2023-06-27 01:44 UTC, zccrs commented on src/private/dmaskeffectnode.cpp
> +    if (binding != 2)
不是2意味着什么呢，这里要体现出来判断的目的，比如 if (binging != 2) 是判定绑定的材质是不是 mask 还是？加上这样的注释，不然单看代码不知道是判断了啥。

2023-06-27 02:10 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +    if (binding != 2)
> 不是2意味着什么呢，这里要体现出来判断的目的，比如 if (binging != 2) 是判定绑定的材质是不是 mask 还是？加上这样的注释，不然单看代码不知道是判断了啥。

现在着色器和继承QSGMaterialRhiShader绑定很紧，qt也是这样写的，我怀疑qt的设计如此

2023-06-27 02:13 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 64, &maskScale, 4);
这里写的有问题，应该是8,
这个是针对ubuf里面 vec2的偏移，这里maskScale的大小刚刚等于 vec2的大小，可以用sizeof，但实际上取的是它内部float[2]的这个数据，

2023-06-27 06:01 UTC, 18202781743 commented on src/private/dmaskeffectnode.cpp
> +        memcpy(buf->data() + 64, &maskScale, 4);
模板函数和QDataStream都不太合适，因为我们一次可能只改变部分值，不太适合动态计算偏移量，

2023-06-30 05:31 UTC, zccrs approved these changes

2023-06-30 05:32 UTC, merged