doc: Add README file in Chinese
linuxdeepin/dtkdeclarative pull request #19
Opened 2022-07-15 10:01 UTC by cccccccb

Briefly add a description file that describes the project.

Log:
Change-Id: I7c2751a4e14f70f1ad0c5bda73190f6614870328

2022-07-18 05:07 UTC, kegechen requested changes

2022-07-18 05:07 UTC, kegechen commented on README_zh_CN.md
> +deepin-tool-kit is licensed under [GPLv3](https://gerrit.uniontech.com/plugins/gitiles/dtkwidget/+/refs/heads/master/LICENSE).
LGPL v3 吧

2022-07-19 02:20 UTC, cccccccb commented on README_zh_CN.md
> +deepin-tool-kit is licensed under [GPLv3](https://gerrit.uniontech.com/plugins/gitiles/dtkwidget/+/refs/heads/master/LICENSE).
已修改

2022-07-19 02:57 UTC, kegechen approved these changes

2022-07-19 03:04 UTC, kegechen approved these changes

2022-07-19 03:05 UTC, merged