fix: DciIcon's size too long
linuxdeepin/dtkdeclarative pull request #246
Opened 2023-11-21 10:19 UTC by 18202781743

DciIcon's size is too long when app doesn't set AA_UseHighDpiPixmaps,
but pixmap will be blur when factor is greater than 1.0,
so app should set AA_UseHighDpiPixmaps.

2023-11-21 10:24 UTC, 18202781743 commented
https://github.com/linuxdeepin/deepin-tweak/pull/39

2023-11-21 10:29 UTC, 18202781743 commented
![企业微信截图_17004590185557](https://github.com/linuxdeepin/dtkdeclarative/assets/20967670/a685ecd6-fbfe-45d8-a4be-852053504bf8)

![image](https://github.com/linuxdeepin/dtkdeclarative/assets/20967670/ef234bb9-29fd-462b-9cbb-5e5613db6e0c)

2023-11-22 01:33 UTC, BLumia approved these changes

2023-11-22 01:34 UTC, BLumia requested changes
当前的提交怎么是空的

2023-11-22 01:42 UTC, BLumia approved these changes

2023-11-22 04:55 UTC, BLumia approved these changes

2023-11-28 05:56 UTC, merged