fix: some build warning
linuxdeepin/dtkdeclarative pull request #25
Opened 2022-07-21 10:17 UTC by cccccccb

1. Ambiguous classes with the same name under different files
2. Obsolete interfaces are wrapped with macro definitions

Log:
Issue: linuxdeepin/developer-center/issues#3316
Change-Id: I3a64b5a19adc8c749a88af4af6c98a5eabde25e4

2022-07-27 03:41 UTC, zccrs approved these changes

2022-07-28 01:51 UTC, zccrs requested changes

2022-07-28 01:51 UTC, zccrs commented on src/private/dquickkeylistener.cpp
> +        keyTexts << modifiers.split("+", Qt::SkipEmptyParts);
"+" 改为 '+'，下面的几个地方同样，就不一一标记了

2022-07-28 01:53 UTC, zccrs requested changes

2022-07-28 01:53 UTC, zccrs commented on src/private/dquickwaterprogressattribute.cpp
> +#if QT_VERSION > QT_VERSION_CHECK(5, 15, 0)
\>= 吗？还是应该 <

2022-07-28 05:09 UTC, cccccccb commented on src/private/dquickkeylistener.cpp
> +        keyTexts << modifiers.split("+", Qt::SkipEmptyParts);
好的

2022-07-28 05:12 UTC, cccccccb commented on src/private/dquickwaterprogressattribute.cpp
> +#if QT_VERSION > QT_VERSION_CHECK(5, 15, 0)
>=， 用指针的方式是在 5.15 新加的，旧版不带指针

2022-07-28 07:10 UTC, zccrs commented on src/private/dquickwaterprogressattribute.cpp
> +#if QT_VERSION > QT_VERSION_CHECK(5, 15, 0)
那就是用 \>= ，不然就没有包含 5.15.0 这个版本

2022-07-28 07:13 UTC, zccrs approved these changes

2022-07-28 10:02 UTC, cccccccb commented
/merge

2022-07-28 10:02 UTC, merged