feat: add corners for BoxShadow
linuxdeepin/dtkdeclarative pull request #294
Opened 2024-03-08 08:19 UTC by 18202781743

We need to set Corners for shadows, which is same as DRoundRectangle.
  TODO: support to set Corners for Shadow image, and updating it's cache png.

2024-03-10 09:06 UTC, BLumia approved these changes

2024-03-11 02:01 UTC, zccrs requested changes

2024-03-11 02:01 UTC, zccrs commented on qt6/src/qml/BoxShadow.qml
> +    property int corners: D.RoundRectangle.AllCorner
用 https://github.com/qt/qtdeclarative/blob/dev/src/quick/items/qquickrectangle_p.h#L136 这种设计，RoundRectangle 后边也可以用 Rectangle 代替实现

2024-03-11 08:25 UTC, zccrs requested changes

2024-03-11 08:25 UTC, zccrs commented on src/private/dquickimageprovider.cpp
> -QUrl DQuickShadowProvider::toUrl(qreal boxSize, qreal cornerRadius, qreal shadowBlur, QColor color,
这个函数是内部的吗，考虑下修改了签名会不会影响兼容性

2024-03-11 11:44 UTC, 18202781743 commented on qt6/src/qml/BoxInsetShadow.qml
> +    property real topLeftRadius: cornerRadius
property real 无法识别undefined, 改为了 variant类型,

2024-03-12 09:46 UTC, merged