feat: add overlay above BackdropBlitter for InWindowBlur
linuxdeepin/dtkdeclarative pull request #328
Opened 2024-04-24 08:24 UTC by 18202781743

it works when Window is transparent.

2024-04-24 09:21 UTC, kegechen reviewed
+1

2024-04-25 02:52 UTC, kegechen approved these changes

2024-04-25 03:03 UTC, zccrs requested changes

2024-04-25 03:03 UTC, zccrs commented on qt6/src/qml/FloatingPanel.qml
> +        overlay: Rectangle {
默认不应该有 overlay，需要使用方主动开启

2024-04-25 08:21 UTC, 18202781743 commented
https://github.com/linuxdeepin/dde-shell/pull/269 dde-shell中规避此问题,

2024-04-25 08:21 UTC, closed without merging