chore: dci icon contorl support animation
linuxdeepin/dtkdeclarative pull request #362
Opened 2024-07-18 08:10 UTC by kegechen

update checkbox / radio dci icon

2024-07-18 10:39 UTC, 18202781743 commented on src/private/dquickdciiconimage.cpp
> -    url.setScheme(QLatin1String("image"));
都不走imageprovider了么?

2024-07-19 01:27 UTC, zccrs requested changes

2024-07-19 01:27 UTC, zccrs commented on src/private/dquickdciiconimage.cpp
> +    player->setDevicePixelRatio(devicePixelRatio);
Needs update when QQuickItem::ItemDevicePixelRatioHasChanged

2024-07-19 01:41 UTC, kegechen commented on src/private/dquickdciiconimage.cpp
> +    player->setDevicePixelRatio(devicePixelRatio);
DQuickIconImage::itemChange(ItemDevicePixelRatioHasChanged) ==> maybeUpdateUrl ==> updatePlayer

2024-07-19 03:10 UTC, kegechen commented on src/private/dquickdciiconimage.cpp
> -    url.setScheme(QLatin1String("image"));
player 支持单帧图片，可以加一个接口禁用这种模式。

2024-07-25 03:39 UTC, kegechen commented
https://github.com/user-attachments/assets/37d358de-fb22-468b-98ef-4db04431a04e

2024-07-25 09:41 UTC, 18202781743 commented on src/private/dquickdciiconimage.cpp
> +    if (iconPath.isEmpty()) {
找不到可以直接调用 DQuickIconImagePrivate::maybeUpdateUrl();
这样的话就fallback到qicon了,

2024-07-30 03:38 UTC, kegechen commented on qt6/src/qml/Switch.qml
> +    hoverEnabled: false // disable hover ==> normal animation
这个也可以，只是为了不播放 `hover` 到 `normal` 的动画，鼠标点击后不挪开时默认是 `hover` 的状态， 这个时候播放normal动画会导致播放成了 `hover` 到 `normal`. 用 `ColorSelector` 也可以

2024-07-30 05:10 UTC, kegechen commented on src/private/dquickdciiconimage.cpp
> +    if (player->property("_d_dci_icon_path").toString() != iconPath) {
这个每次都是重新构造一个 `DDciIcon`， 只能说在 `DQuickDciIconImageItemPrivate` 加一个 `iconPathCache`

2024-07-31 01:12 UTC, merged