chore: ajust window flags
linuxdeepin/dtkdeclarative pull request #380
Opened 2024-08-19 06:29 UTC by kegechen

fix window flags is always Qt::Window

2024-08-20 02:57 UTC, 18202781743 commented on src/dquickwindow.cpp
> +        fixTopLevelWindowFlags(windowFlags);
这个行为,应该让window的创建者自己设置吧?

2024-08-20 03:32 UTC, kegechen commented on src/dquickwindow.cpp
> +        fixTopLevelWindowFlags(windowFlags);
widget 里面是 qwidgetwindow 主动做了这个事，默认窗口只有  `Qt::Window` 这个 `flag`

2024-08-21 01:24 UTC, FeiWang1119 submitted a review, later dismissed

2024-09-25 06:04 UTC, kegechen commented on src/dquickwindow.cpp
> +        fixTopLevelWindowFlags(windowFlags);
`flags: Qt.Window | Qt.WindowCloseButtonHint | Qt.WindowTitleHint | Qt.WindowMinimizeButtonHint | Qt.WindowMaximizeButtonHint`
应用 倒是也可以这么设置

2024-10-08 08:49 UTC, 18202781743 commented on src/dquickwindow.cpp
> +        fixTopLevelWindowFlags(windowFlags);
这个操作会不会覆盖了应用在Window设置的flags，

2024-10-08 08:53 UTC, zccrs requested changes

2024-10-08 08:53 UTC, zccrs commented on src/dquickwindow.cpp
> +                 |Qt::WindowMaximizeButtonHint|Qt::WindowCloseButtonHint;
` | `

2024-10-08 08:53 UTC, zccrs commented on src/dquickwindow.cpp
> +    case Qt::Dialog:
Q_FALLTHROUGH

2024-10-08 08:54 UTC, zccrs commented
这是解决啥bug？

2024-10-25 06:14 UTC, kegechen commented
> 这是解决啥bug？

不算是bug，应用如果直接用dtk的 window， 就算有标题栏默认是没有最大最小关闭这些按钮的。需要手动设置 flags 才行。这里 参考widget 主动设置一下flags，当然也可以不加，要求用户自己设置。 改的就是一个默认行为而已

2024-12-13 01:46 UTC, closed without merging