fix: tooltip crashed while application exit
linuxdeepin/dtkdeclarative pull request #381
Opened 2024-08-19 06:44 UTC by FeiWang1119

fix the clean job of blurnode

Issue: https://github.com/linuxdeepin/dtk/issues/193

2024-08-20 09:08 UTC, kegechen commented
/approve

2024-08-21 06:57 UTC, kegechen commented
https://github.com/linuxdeepin/dtkdeclarative/pull/385/files

2024-08-22 03:27 UTC, 18202781743 commented on src/private/dquickinwindowblur.cpp
> +            connect(this, &QObject::destroyed, this, [node, blurNode](){
正常情况下, quickitem销毁了, node应该也被销毁把, 不需要去重置这个callback,

2024-08-26 02:46 UTC, zccrs requested changes

2024-08-26 02:46 UTC, zccrs commented on src/private/dquickinwindowblur.cpp
> +            connect(this, &QObject::destroyed, this, [node, blurNode](){
node可能会比item晚一点销毁，因为渲染可能是在一个新线程里，如果在渲染中销毁了item，它的node是不会立即销毁的。但是这里也不应该这样改，应该在 node 调用 callback之前检查 setRenderCallback中给出来的第二个参数。

2024-09-11 06:35 UTC, kegechen commented
暂时close，不是这里的问题 @FeiWang1119

2024-09-11 06:35 UTC, closed without merging