fix: crashed on palette destroyed
linuxdeepin/dtkdeclarative pull request #385
Opened 2024-08-21 06:56 UTC by kegechen

do not set value if palette and color invalid

2024-08-21 07:51 UTC, 18202781743 commented on src/private/dquickcontrolpalette.cpp
> +    if (!palette && !color.isValid())
这个函数之前是支持paletet为nullptr的, 有地方明确传入的palette为nullptr, 这会导致调用失效,

2024-08-26 02:43 UTC, zccrs requested changes

2024-08-26 02:43 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +    if (QCoreApplication::closingDown() || (m_control && !m_control->window()))
后续的操作哪里依赖了 window 呢？
另外，如果这里判断了window是否存在，后续 m_control 是可能重新被添加到一个新的window里的，这时候应该触发属性的更新。

2024-08-27 09:48 UTC, kegechen commented on src/private/dquickcontrolpalette.cpp
> +    if (QCoreApplication::closingDown() || DQMLGlobalObjectPrivate::g_appAboutToQuit)
closingDown 太晚了，，aboutToQuit 时就应该停止了

2024-10-17 01:41 UTC, zccrs requested changes

2024-10-17 01:41 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +    if (QCoreApplication::closingDown() || DQMLGlobalObjectPrivate::g_appAboutToQuit)
用 QCoreApplicationPrivate::aboutToQuitEmitted 做判断行不行？

2024-10-22 03:03 UTC, kegechen commented on src/private/dquickcontrolpalette.cpp
> +    if (QCoreApplication::closingDown() || DQMLGlobalObjectPrivate::g_appAboutToQuit)
> 用 QCoreApplicationPrivate::aboutToQuitEmitted 做判断行不行？

可以需要用 `#define protected public` 黑魔法

2024-10-22 08:54 UTC, 18202781743 commented on src/private/dquickcontrolpalette.cpp
> +    auto appriv = static_cast<QCoreApplicationPrivate*>(qApp->QCoreApplication::d_ptr.data());
auto prv = dynamic_cast<QCoreApplicationPrivate *>(QObjectPrivate::get(qApp));
    qDebug() << prv->aboutToQuitEmitted;

2024-11-13 02:29 UTC, zccrs approved these changes

2024-11-20 05:34 UTC, kegechen commented
doxygen 安装 `libgcc-s1 13.2.0-3deepin2` 错误，暂时忽略

2024-11-20 06:08 UTC, merged