fix: placeholder text horizontalAlignment not work
linuxdeepin/dtkdeclarative pull request #402
Opened 2024-10-08 08:12 UTC by kegechen

remove loader

2024-10-08 08:55 UTC, zccrs reviewed
没有看到哪里有使用 `horizontalAlignment` 呀

2024-10-09 01:48 UTC, kegechen commented
> 没有看到哪里有使用 `horizontalAlignment` 呀

主要是 placeholdertext updateAlignment时 parentitem转换失败。不需要单独设置这个 textfield 里面设置就可以。
```qml
TextField {
            placeholderText: qsTr("test here")
            horizontalAlignment: Text.AlignHCenter 
        }
```

```cpp
void QQuickPlaceholderText::updateAlignment()
{
    if (QQuickTextInput *input = qobject_cast<QQuickTextInput *>(parentItem())) {
        if (QQuickTextInputPrivate::get(input)->hAlignImplicit)
            resetHAlign();
        else
            setHAlign(static_cast<HAlignment>(input->hAlign()));
    } else if (QQuickTextEdit *edit = qobject_cast<QQuickTextEdit *>(parentItem())) {
        if (QQuickTextEditPrivate::get(edit)->hAlignImplicit)
            resetHAlign();
        else
            setHAlign(static_cast<HAlignment>(edit->hAlign()));
    } else {
        resetHAlign();
    }
}
```

2024-10-09 02:40 UTC, 18202781743 submitted a review, later dismissed

2024-10-10 05:20 UTC, zccrs requested changes

2024-10-10 05:20 UTC, zccrs commented on qt6/src/qml/TextField.qml
> +    // see QQuickPlaceholderText::updateAlignment()
这里可以写清楚，QQuickPlaceholderText 会假定他的 parent item 是 QQuickText，用了 Loader 会影响它的 parentItem

2024-10-16 07:10 UTC, merged