fix: Boxshadow displays abnormally in fractional scaling scenarios
linuxdeepin/dtkdeclarative pull request #420
Opened 2024-11-22 08:57 UTC by lbwtw

- Temporary solution

2024-11-22 09:10 UTC, zccrs requested changes

2024-11-22 09:10 UTC, zccrs commented on src/private/dquickborderimage.cpp
> +        value.realValue != static_cast<QQuickBorderImagePrivate *>(QQuickItemPrivate::get(this))->devicePixelRatio) {
只需要判断 change 就行

2024-11-22 09:10 UTC, zccrs commented on src/private/dquickborderimage.cpp
> +    :QQuickBorderImage(parent)
`: ` 别忘记了空格

2024-11-22 09:10 UTC, zccrs commented on src/private/dquickborderimage.h
_p.h

2024-11-22 09:10 UTC, zccrs commented on src/private/dquickborderimage.h
> +    DQuickBorderImage(QQuickItem *parent=nullptr);
explicit

2024-11-22 10:02 UTC, zccrs approved these changes

2024-11-23 02:05 UTC, 18202781743 approved these changes

2024-11-29 04:45 UTC, merged