fix: titlebar left margin not set
linuxdeepin/dtkdeclarative pull request #46
Opened 2022-11-02 08:22 UTC by kegechen

set titlebar layout leftmargin 10

Bug: https://pms.uniontech.com/bug-view-168245.html
Change-Id: Id79629c1ec6d5378eb1522f5602433a640832027

2022-11-02 08:55 UTC, zccrs requested changes

2022-11-02 08:55 UTC, zccrs commented on src/qml/DialogTitleBar.qml
> +            Layout.leftMargin: 10
这种控制UI显示的常量放到 Style.qml 中统一定义

2022-11-02 09:25 UTC, kegechen commented on src/qml/DialogTitleBar.qml
> +            Layout.leftMargin: 10
deon

2022-11-03 01:52 UTC, kegechen commented on src/qml/DialogTitleBar.qml
> +            Layout.leftMargin: 10
done

2022-11-03 07:48 UTC, zccrs approved these changes

2022-11-03 07:51 UTC, merged