fix: Modify appload's plugin path
linuxdeepin/dtkdeclarative pull request #54
Opened 2022-11-28 08:33 UTC by 18202781743

using 'appid' filed to identify AppLoad's plugin instead of
plugin's name.
  Modify DTK_QML_APP_PLUGIN_PATH's value in dtkdeclarative's
cmake and pri.
  AppLoad find plugin's path is the order:
custom's addPluginPath ->
env: DTK_QML_PLUGIN_PATH ->
env: LD_LIBRARY_PATH/DTK_QML_APP_PLUGIN_SUBPATH ->
dtkdeclarative install path: DTK_QML_APP_PLUGIN_PATH,
  We suggest user should set plugin's path using 'addPluginPath'.

Log: 修改插件的标识信息，安装路径，查找路径
Influence: 使用了AppLoader的qml应用若没适配可能崩溃
Change-Id: I24260967a814caa94000a63ee91bdbe223560c78

2022-11-28 08:34 UTC, 18202781743 commented
/review @kegechen @zccrs

2022-11-29 06:46 UTC, kegechen commented on src/dapploader.h
> +    void addPluginPath(const QString &dir);
是否需要加一个pluginpaths的接口

2022-11-29 06:46 UTC, kegechen commented on examples/qml-app-template/src/preloadplugin/plugin.json
> +    "appid": "org.deepin.%{ProjectName}"
ProjectName 啥时候赋值？

2022-11-29 06:46 UTC, kegechen commented on examples/qml-app-template/src/maincomponentplugin/plugin.json
> +    "appid": "org.deepin.%{ProjectName}"
同下

2022-11-29 10:31 UTC, 18202781743 commented on src/dapploader.h
> +    void addPluginPath(const QString &dir);
应用应该用不到，因为没有提供setPluginPath接口，

2022-11-29 10:32 UTC, 18202781743 commented on examples/qml-app-template/src/preloadplugin/plugin.json
> +    "appid": "org.deepin.%{ProjectName}"
向导填充的项目名称

2022-11-30 02:33 UTC, zccrs requested changes

2022-11-30 02:33 UTC, zccrs commented on qmlplugin/qmlplugin_plugin.cpp
> +#include <dapploader.h>
没有 DAppLoader 的头文件吗

2022-11-30 02:33 UTC, zccrs commented on src/private/dapploader_p.h
> +    template<class T> T *loadInstance() const;
这个函数是明确不会在项目外被使用吗？不然模板的实现放到cpp里就不合适了

2022-11-30 02:33 UTC, zccrs commented on src/private/dapploader_p.h
> +    QStringList buildinPluginPaths() const;
是不是可以是 static 的

2022-11-30 03:35 UTC, 18202781743 commented on src/private/dapploader_p.h
> +    template<class T> T *loadInstance() const;
这个是个内部函数，现在把它标记为私有的吧，

2022-11-30 03:35 UTC, 18202781743 commented on qmlplugin/qmlplugin_plugin.cpp
> +#include <dapploader.h>
失误，这段是测试代码，不应该提交的

2022-11-30 03:35 UTC, 18202781743 commented on src/private/dapploader_p.h
> +    QStringList buildinPluginPaths() const;
好的，

2022-11-30 03:37 UTC, 18202781743 commented on src/dapploader.h
> +    void addPluginPath(const QString &dir);
还是加上吧，方便应用测试

2022-12-06 08:17 UTC, kegechen approved these changes

2022-12-06 08:25 UTC, 18202781743 commented
/merge

2022-12-07 05:05 UTC, kegechen approved these changes

2022-12-20 08:50 UTC, zccrs approved these changes

2022-12-20 08:53 UTC, merged