fix: Window.enabled is invalid
linuxdeepin/dtkdeclarative pull request #57
Opened 2022-12-02 06:54 UTC by 18202781743

it's exist when application is startup automatically and wm's
flag fetch `_deepin_no_titlebar` info by error in platformplugin.
  wm's flag is updated when recvs QXcbAtom::_NET_SUPPORTED, and
then emit hasNoTitlebarChanged signal.
  related code is in dde-qt5platformplugins:
  XcbNativeEventFilter::nativeEventFilter(QXcbAtom::_NET_SUPPORTED)
 -> DXcbWmSupport::updateNetWMAtoms
 -> DXcbWmSupport::updateHasNoTitlebar

Log: xcb延迟更新hasNoTitlebar，导致dtkdeclarative的Window.enabled错误
Bug: https://pms.uniontech.com/bug-view-168517.html
Influence: qml重构的授权客户端开机自启时，标题显示错误
Change-Id: I8481fae88a9effe29110647e84c43ebc0bec9558

2022-12-02 06:54 UTC, 18202781743 commented
/review @kegechen @zccrs

2022-12-02 06:56 UTC, kegechen approved these changes

2022-12-02 07:19 UTC, zccrs requested changes

2022-12-02 07:19 UTC, zccrs commented on src/dquickwindow.cpp
> +        QObject::connect(DWindowManagerHelper::instance(), &DWindowManagerHelper::hasNoTitlebarChanged, this,
这个connect可能会重复链接，所以不应该在这里connect，或者加一下 Qt::UniqueConnection 。

2022-12-02 07:19 UTC, zccrs commented on src/dquickwindow.cpp
> +                d->ensurePlatformHandle();
在调用它之前还是应当判断一下当前是否为 isEnabled()

2022-12-02 09:46 UTC, 18202781743 commented on src/dquickwindow.cpp
> +        QObject::connect(DWindowManagerHelper::instance(), &DWindowManagerHelper::hasNoTitlebarChanged, this,
好的，

2022-12-02 09:48 UTC, 18202781743 commented on src/dquickwindow.cpp
> +                d->ensurePlatformHandle();
应该可以直接判断explicitEnable，
另外isEnabled()没有加上explicitEnable的判断，应该没有必要

2022-12-05 02:14 UTC, zccrs approved these changes

2022-12-06 02:50 UTC, merged