fix: palette invalid when Control's enable changed
linuxdeepin/dtkdeclarative pull request #58
Opened 2022-12-06 07:44 UTC by 18202781743

`palette.windowText: palette.highlight` causes binding loop,
`palette.windowText: D.colorSelector.textColor` alse cause that if textColor is using palette.highlight as return value.
  We shouldn't use palette.highlight as palette's windowText in
this way, and here We need D.ColorSelector.textColor as DciIcon.palette.foreground.
  We add a `Palette` attached property to translate from QPalette
to DciPalette.

Log: palette循环绑定，导致enable切换时，颜色获取失效
Bug: https://pms.uniontech.com/bug-view-168405.html Influence: 所有使用了高亮色作为字体颜色的按钮，当按钮切换enabled后，颜色
可能无法正常显示

Change-Id: Ib12ca6afd82e6203c9a95502872ef7302ff089e3

2022-12-06 07:44 UTC, 18202781743 commented
/review @kegechen

2022-12-06 09:39 UTC, zccrs requested changes

2022-12-06 09:39 UTC, zccrs commented on src/qml/SliderTipItem.qml
> +            color: control.D.ColorSelector.textColor
为什么变成了直接设置它的color属性，这样跟原来的逻辑就不一样了

2022-12-06 09:39 UTC, zccrs commented on src/qml/settings/NavigationTitle.qml
> +        color: checked ? D.ColorSelector.checkedTextColor : undefined
同上。而且这里的颜色设置从父对象中移动到了Label里是为什么？

2022-12-06 09:39 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +    QColor m_foreground;
定义在这里的成员变量就没必要加 m_ 前缀了，因为不会与其他的命名有冲突。

2022-12-06 09:39 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +    : QObject (parent)
这里的括号前面不用空格

2022-12-06 09:39 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +    if (!_d_isControlItem(item) && item->property("palette").isNull())
应该是判断 palette 属性的 QVariant 能不能转换为 QPalette

2022-12-06 09:39 UTC, zccrs commented on src/private/dquickcontrolpalette.cpp
> +    connect(parent, SIGNAL(paletteChanged()), this, SIGNAL(paletteChanged()));
如果链接失败了，要给一个警告

2022-12-06 09:39 UTC, zccrs commented on src/qml/ActionButton.qml
> +    D.Palette.foreground: pressed ? D.ColorSelector.textColor : undefined
改成这样之后，Button的palette.widowText 会在哪里被设置呀？

2022-12-12 00:55 UTC, 18202781743 commented
palette.windowText: D.colorSelector.textColor不会造成循环绑定，应该是Qt的问题导致enabled切换，其QPalette的currentColorGroup错误，已提交patch让Qt那边确认下

2022-12-12 00:55 UTC, closed without merging